name: cicd pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy-to-my-AWS-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Display the code
        run: ls -la

      - name: Display more commands
        run: |
          ls -la
          hostnamectl



  deploy-to-my-AWS-server-01:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Display the code
        run: ls -la

      - name: Display more commands
        run: |
          ls -la
          hostnamectl
  
  deploy-to-my-AWS-server-02:
    needs: deploy-to-my-AWS-server-01
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Display the code
        run: ls -la

      - name: Display more commands
        run: |
          ls -la
          hostnamectl
          